#define REDIS_GIT_SHA1 "cae9b24f"
#define REDIS_GIT_DIRTY "0"
#define REDIS_BUILD_ID "sendai-1764916845"
#include "version.h"
#define REDIS_BUILD_ID_RAW REDIS_VERSION REDIS_BUILD_ID REDIS_GIT_DIRTY REDIS_GIT_SHA1
