#define REDIS_GIT_SHA1 "c7259466"
#define REDIS_GIT_DIRTY "43"
#define REDIS_BUILD_ID "sendai-1764923102"
#include "version.h"
#define REDIS_BUILD_ID_RAW REDIS_VERSION REDIS_BUILD_ID REDIS_GIT_DIRTY REDIS_GIT_SHA1
